/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/failover/tier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tier */
        get: operations["tier_failover_tier_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Completions */
        post: operations["completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FailoverStatus */
        FailoverStatus: {
            /** Elected Host */
            elected_host?: string | null;
            /**
             * In Flight
             * @default 0
             */
            in_flight: number;
            /** Reachable Members */
            reachable_members?: string[];
            /** Snapshot Expires At */
            snapshot_expires_at?: string | null;
            tier: components["schemas"]["FailoverTier"];
            /**
             * Unavailable Capabilities
             * @default []
             */
            unavailable_capabilities: string[];
        };
        /**
         * FailoverTier
         * @enum {string}
         */
        FailoverTier: "full" | "degraded_inference" | "minimal";
        /** GatewayModel */
        GatewayModel: {
            /** Coire Context Window */
            coire_context_window?: number | null;
            /** Coire Description */
            coire_description?: string | null;
            /**
             * Coire Load State
             * @enum {string}
             */
            coire_load_state: "loaded" | "loading" | "cold";
            /** @default studio */
            coire_source: components["schemas"]["ModelSource"];
            /** Coire Tags */
            coire_tags?: string[];
            /** Created */
            created: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Object
             * @default model
             * @constant
             */
            object: "model";
            /**
             * Owned By
             * @default coire
             * @constant
             */
            owned_by: "coire";
        };
        /** GatewayModelList */
        GatewayModelList: {
            /** Data */
            data: components["schemas"]["GatewayModel"][];
            /**
             * Object
             * @default list
             * @constant
             */
            object: "list";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ModelSource
         * @enum {string}
         */
        ModelSource: "studio" | "openai" | "anthropic";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    tier_failover_tier_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailoverStatus"];
                };
            };
        };
    };
    completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: {
                "cf-access-jwt-assertion"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_v1_models_get: {
        parameters: {
            query?: never;
            header?: {
                "cf-access-jwt-assertion"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayModelList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
