/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Read the audit log. There is no route that writes, edits or deletes one.
         */
        get: operations["list_audit_api_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Engines */
        get: operations["list_engines_api_v1_admin_engines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/engines/{engine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Engine */
        get: operations["get_engine_api_v1_admin_engines__engine_id__get"];
        put?: never;
        post?: never;
        /**
         * Unload Engine
         * @description Unload. Works for an orphan too, which is how an operator clears one (US4 scenario 2).
         */
        delete: operations["unload_engine_api_v1_admin_engines__engine_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_admin_models_get"];
        put?: never;
        /**
         * Add Model
         * @description Add a model from a Hugging Face repository and start acquiring it.
         */
        post: operations["add_model_api_v1_admin_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_api_v1_admin_models__model_id__get"];
        put?: never;
        post?: never;
        /** Delete Model */
        delete: operations["delete_model_api_v1_admin_models__model_id__delete"];
        options?: never;
        head?: never;
        /** Update Model */
        patch: operations["update_model_api_v1_admin_models__model_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}/job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_admin_models__model_id__job_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Model
         * @description Load a model on a node. Exercised by tests and the console; user traffic is feature 003.
         */
        post: operations["load_model_api_v1_admin_models__model_id__load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire Model */
        post: operations["retire_model_api_v1_admin_models__model_id__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Model */
        post: operations["retry_model_api_v1_admin_models__model_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Nodes
         * @description Declared nodes with the last status the prober received, their engines and jobs.
         */
        get: operations["list_nodes_api_v1_admin_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Models the caller may see, with live load state.
         *
         *     An admin sees everything; anyone else sees only published, ready, unentitled models
         *     (spec US5 scenario 1). Existence is not disclosed: an unpublished model is simply absent.
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Node
         * @description Register or re-register a declared node. Idempotent on name.
         */
        post: operations["register_node_api_v1_nodes_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Aggregate health.
         *
         *     Postgres is the only critical dependency: without it the control plane has no system of
         *     record, so its failure is `unhealthy` (HTTP 503). Everything else degrades.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ready
         * @description Liveness. Deliberately checks nothing external.
         */
        get: operations["get_ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Completions */
        post: operations["chat_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anthropic Messages */
        post: operations["anthropic_messages_v1_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnthropicMessage */
        AnthropicMessage: {
            /** Content */
            content: string | {
                [key: string]: unknown;
            }[];
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** AnthropicMessagesRequest */
        AnthropicMessagesRequest: {
            /**
             * Coire Wait For Model
             * @default true
             */
            coire_wait_for_model: boolean;
            /** Max Tokens */
            max_tokens: number;
            /** Messages */
            messages: components["schemas"]["AnthropicMessage"][];
            /**
             * Model
             * Format: uuid
             */
            model: string;
            /** Stop Sequences */
            stop_sequences?: string[] | null;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /** System */
            system?: string | {
                [key: string]: unknown;
            }[] | null;
            /** Temperature */
            temperature?: number | null;
            /** Tool Choice */
            tool_choice?: {
                [key: string]: unknown;
            } | null;
            /** Tools */
            tools?: {
                [key: string]: unknown;
            }[] | null;
            /** Top P */
            top_p?: number | null;
        };
        /**
         * AuditOutcome
         * @enum {string}
         */
        AuditOutcome: "ok" | "refused" | "error";
        /** AuditRecord */
        AuditRecord: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            outcome: components["schemas"]["AuditOutcome"];
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /**
         * CapabilityProfile
         * @description Declared model behaviour. Harness behaviour is selected from this, never from a model
         *     name (Principle V).
         */
        CapabilityProfile: {
            /**
             * Chat Template Present
             * @default false
             */
            chat_template_present: boolean;
            /** Context Window */
            context_window?: number | null;
            /**
             * Parallel Tools
             * @default false
             */
            parallel_tools: boolean;
            /** @default none */
            reasoning: components["schemas"]["Reasoning"];
            /** @default none */
            structured_output: components["schemas"]["StructuredOutput"];
            /** @default none */
            tool_calling: components["schemas"]["ToolCalling"];
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        };
        /**
         * CapabilityProfileUpdate
         * @description The admin-editable subset. `verified` is absent by construction, so a request carrying
         *     it is rejected as an unknown field rather than silently ignored.
         */
        CapabilityProfileUpdate: {
            /** Context Window */
            context_window?: number | null;
            /** Parallel Tools */
            parallel_tools?: boolean | null;
            reasoning?: components["schemas"]["Reasoning"] | null;
            structured_output?: components["schemas"]["StructuredOutput"] | null;
            tool_calling?: components["schemas"]["ToolCalling"] | null;
        };
        /** ChatCompletionRequest */
        ChatCompletionRequest: {
            /**
             * Coire Wait For Model
             * @default true
             */
            coire_wait_for_model: boolean;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /**
             * Model
             * Format: uuid
             */
            model: string;
            /** Response Format */
            response_format?: {
                [key: string]: unknown;
            } | null;
            /** Stop */
            stop?: string | string[] | null;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /** Temperature */
            temperature?: number | null;
            /** Tool Choice */
            tool_choice?: unknown;
            /** Tools */
            tools?: {
                [key: string]: unknown;
            }[] | null;
            /** Top P */
            top_p?: number | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string | null;
            /** Name */
            name?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Tool Call Id */
            tool_call_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** GatewayModel */
        GatewayModel: {
            /** Coire Context Window */
            coire_context_window?: number | null;
            /** Coire Description */
            coire_description?: string | null;
            /**
             * Coire Load State
             * @enum {string}
             */
            coire_load_state: "loaded" | "loading" | "cold";
            /** Coire Tags */
            coire_tags?: string[];
            /** Created */
            created: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Object
             * @default model
             * @constant
             */
            object: "model";
            /**
             * Owned By
             * @default coire
             * @constant
             */
            owned_by: "coire";
        };
        /** GatewayModelList */
        GatewayModelList: {
            /** Data */
            data: components["schemas"]["GatewayModel"][];
            /**
             * Object
             * @default list
             * @constant
             */
            object: "list";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description `GET /health` — the aggregate. HTTP 503 when `status` is `unhealthy`.
         */
        HealthResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Nodes */
            nodes?: components["schemas"]["ServiceHealth"][];
            /** Services */
            services?: components["schemas"]["ServiceHealth"][];
            status: components["schemas"]["HealthStatus"];
            /** Version */
            version: string;
        };
        /**
         * HealthStatus
         * @description Aggregate verdict for the control plane.
         * @enum {string}
         */
        HealthStatus: "healthy" | "degraded" | "unhealthy";
        /**
         * LoadState
         * @enum {string}
         */
        LoadState: "loaded" | "loading" | "cold";
        /** ModelAddRequest */
        ModelAddRequest: {
            /** Description */
            description?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Idle Ttl Seconds */
            idle_ttl_seconds?: number | null;
            /**
             * Placement Policy
             * @default single:auto
             */
            placement_policy: string;
            /** Repo Id */
            repo_id: string;
            /** Tags */
            tags?: components["schemas"]["Tag"][];
        };
        /**
         * ModelListing
         * @description The user-facing shape.
         *
         *     Deliberately narrow: no paths, no copies, no failure reasons, no repo id. What a user may
         *     see about a model is what the picker needs to choose one.
         */
        ModelListing: {
            capability_profile: components["schemas"]["CapabilityProfile"];
            /** Context Window */
            context_window?: number | null;
            /** Description */
            description?: string | null;
            /** Display Name */
            display_name: string;
            /** Estimated Warmup Seconds */
            estimated_warmup_seconds?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            load_state: components["schemas"]["LoadState"];
            /** Loaded On */
            loaded_on?: string[];
            /** Precision */
            precision: string;
            /** Tags */
            tags?: components["schemas"]["Tag"][];
        };
        /**
         * ModelUpdateRequest
         * @description Curation. Every field is optional; absent means unchanged.
         *
         *     `chat_template` is tri-state and cannot be expressed with a plain `| None` default, so
         *     absence is spelled with a sentinel: the field is `str | None` and "not supplied" is
         *     detected with `model_fields_set`.
         */
        ModelUpdateRequest: {
            capability_profile?: components["schemas"]["CapabilityProfileUpdate"] | null;
            /** Chat Template */
            chat_template?: string | null;
            /** Description */
            description?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Entitlement */
            entitlement?: string[] | null;
            /** Idle Ttl Seconds */
            idle_ttl_seconds?: number | null;
            /** Placement Policy */
            placement_policy?: string | null;
            /** Tags */
            tags?: components["schemas"]["Tag"][] | null;
            visibility?: components["schemas"]["Visibility"] | null;
        };
        /**
         * Node
         * @description A declared Studio, as persisted and returned by the registration endpoint.
         */
        Node: {
            /** Agent Version */
            agent_version: string;
            /** Disk Total Bytes */
            disk_total_bytes: number;
            /** Egress Address */
            egress_address?: string | null;
            /** Gpu Cores */
            gpu_cores?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Memory Total Bytes */
            memory_total_bytes: number;
            /**
             * Mesh Address
             * Format: ipv4
             */
            mesh_address: string;
            /** Name */
            name: string;
            /** @default unknown */
            reachability: components["schemas"]["Reachability"];
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            role: components["schemas"]["NodeRole"];
        };
        /**
         * NodeRegistration
         * @description `POST /api/v1/nodes/register` request body.
         */
        NodeRegistration: {
            /** Agent Version */
            agent_version: string;
            /** Disk Total Bytes */
            disk_total_bytes: number;
            /** Egress Address */
            egress_address?: string | null;
            /** Gpu Cores */
            gpu_cores?: number | null;
            /** Memory Total Bytes */
            memory_total_bytes: number;
            /**
             * Mesh Address
             * Format: ipv4
             */
            mesh_address: string;
            /** Name */
            name: string;
            /**
             * Token
             * Format: password
             */
            token: string;
        };
        /**
         * NodeRole
         * @enum {string}
         */
        NodeRole: "studio" | "core";
        /**
         * Reachability
         * @description Feature 000 sets only HEALTHY/UNREACHABLE/UNKNOWN; DEGRADED arrives with feature 009.
         * @enum {string}
         */
        Reachability: "healthy" | "degraded" | "unreachable" | "unknown";
        /**
         * ReadyResponse
         * @description `GET /ready` — liveness only. Deliberately checks nothing external (FR-009).
         */
        ReadyResponse: {
            /**
             * Ready
             * @default true
             * @constant
             */
            ready: true;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /**
         * Reasoning
         * @enum {string}
         */
        Reasoning: "none" | "thinking" | "hybrid";
        /**
         * ServiceHealth
         * @description One dependency's health as observed by the aggregate probe.
         */
        ServiceHealth: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Detail */
            detail?: string | null;
            /** Healthy */
            healthy: boolean;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Name */
            name: string;
        };
        /**
         * StructuredOutput
         * @enum {string}
         */
        StructuredOutput: "none" | "json_mode" | "json_schema";
        /**
         * Tag
         * @description The picker's grouping vocabulary (ARCHITECTURE.md section 3.2).
         * @enum {string}
         */
        Tag: "coding" | "general" | "reasoning" | "vision" | "image";
        /**
         * ToolCalling
         * @enum {string}
         */
        ToolCalling: "none" | "prompted" | "native";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Visibility
         * @enum {string}
         */
        Visibility: "admin_only" | "published";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_api_v1_admin_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                target_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_engines_api_v1_admin_engines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_engine_api_v1_admin_engines__engine_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unload_engine_api_v1_admin_engines__engine_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_admin_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    add_model_api_v1_admin_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_v1_admin_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_api_v1_admin_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_api_v1_admin_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_admin_models__model_id__job_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_model_api_v1_admin_models__model_id__load_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: string;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_model_api_v1_admin_models__model_id__retire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_model_api_v1_admin_models__model_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_nodes_api_v1_admin_nodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListing"][];
                };
            };
        };
    };
    register_node_api_v1_nodes_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeRegistration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    chat_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anthropic_messages_v1_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnthropicMessagesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayModelList"];
                };
            };
        };
    };
}
