/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Read the audit log. There is no route that writes, edits or deletes one.
         */
        get: operations["list_audit_api_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Engines */
        get: operations["list_engines_api_v1_admin_engines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/engines/{engine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Engine */
        get: operations["get_engine_api_v1_admin_engines__engine_id__get"];
        put?: never;
        post?: never;
        /**
         * Unload Engine
         * @description Unload. Works for an orphan too, which is how an operator clears one (US4 scenario 2).
         */
        delete: operations["unload_engine_api_v1_admin_engines__engine_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_admin_models_get"];
        put?: never;
        /**
         * Add Model
         * @description Add a model from a Hugging Face repository and start acquiring it.
         */
        post: operations["add_model_api_v1_admin_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_api_v1_admin_models__model_id__get"];
        put?: never;
        post?: never;
        /** Delete Model */
        delete: operations["delete_model_api_v1_admin_models__model_id__delete"];
        options?: never;
        head?: never;
        /** Update Model */
        patch: operations["update_model_api_v1_admin_models__model_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}/job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_admin_models__model_id__job_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Model
         * @description Load a model on a node. Exercised by tests and the console; user traffic is feature 003.
         */
        post: operations["load_model_api_v1_admin_models__model_id__load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire Model */
        post: operations["retire_model_api_v1_admin_models__model_id__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/models/{model_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Model */
        post: operations["retry_model_api_v1_admin_models__model_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/network/links/studios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Studio Data Link */
        get: operations["studio_data_link_api_v1_admin_network_links_studios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Nodes
         * @description Declared nodes with the last status the prober received, their engines and jobs.
         */
        get: operations["list_nodes_api_v1_admin_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Models the caller may see, with live load state.
         *
         *     An admin sees everything; anyone else sees only published, ready, unentitled models
         *     (spec US5 scenario 1). Existence is not disclosed: an unpublished model is simply absent.
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Node
         * @description Register or re-register a declared node. Idempotent on name.
         */
        post: operations["register_node_api_v1_nodes_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Aggregate health.
         *
         *     Postgres is the only critical dependency: without it the control plane has no system of
         *     record, so its failure is `unhealthy` (HTTP 503). Everything else degrades.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ready
         * @description Liveness. Deliberately checks nothing external.
         */
        get: operations["get_ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Completions */
        post: operations["chat_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anthropic Messages */
        post: operations["anthropic_messages_v1_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnthropicMessage */
        AnthropicMessage: {
            /** Content */
            content: string | {
                [key: string]: unknown;
            }[];
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** AnthropicMessagesRequest */
        AnthropicMessagesRequest: {
            /**
             * Coire Wait For Model
             * @default true
             */
            coire_wait_for_model: boolean;
            /** Container */
            container?: string | {
                [key: string]: unknown;
            } | null;
            /** Context Management */
            context_management?: {
                [key: string]: unknown;
            } | null;
            /** Max Tokens */
            max_tokens: number;
            /** Mcp Servers */
            mcp_servers?: {
                [key: string]: unknown;
            }[] | null;
            /** Messages */
            messages: components["schemas"]["AnthropicMessage"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Model
             * Format: uuid
             */
            model: string;
            /** Output Config */
            output_config?: {
                [key: string]: unknown;
            } | null;
            /** Service Tier */
            service_tier?: string | null;
            /** Stop Sequences */
            stop_sequences?: string[] | null;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /** System */
            system?: string | {
                [key: string]: unknown;
            }[] | null;
            /** Temperature */
            temperature?: number | null;
            /** Thinking */
            thinking?: {
                [key: string]: unknown;
            } | null;
            /** Tool Choice */
            tool_choice?: {
                [key: string]: unknown;
            } | null;
            /** Tools */
            tools?: {
                [key: string]: unknown;
            }[] | null;
            /** Top K */
            top_k?: number | null;
            /** Top P */
            top_p?: number | null;
        };
        /**
         * AuditOutcome
         * @enum {string}
         */
        AuditOutcome: "ok" | "refused" | "error";
        /** AuditRecord */
        AuditRecord: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            outcome: components["schemas"]["AuditOutcome"];
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /**
         * CapabilityProfile
         * @description Declared model behaviour. Harness behaviour is selected from this, never from a model
         *     name (Principle V).
         */
        CapabilityProfile: {
            /**
             * Chat Template Present
             * @default false
             */
            chat_template_present: boolean;
            /** Context Window */
            context_window?: number | null;
            /**
             * Parallel Tools
             * @default false
             */
            parallel_tools: boolean;
            /** @default none */
            reasoning: components["schemas"]["Reasoning"];
            /** @default none */
            structured_output: components["schemas"]["StructuredOutput"];
            /** @default none */
            tool_calling: components["schemas"]["ToolCalling"];
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        };
        /**
         * CapabilityProfileUpdate
         * @description The admin-editable subset. `verified` is absent by construction, so a request carrying
         *     it is rejected as an unknown field rather than silently ignored.
         */
        CapabilityProfileUpdate: {
            /** Context Window */
            context_window?: number | null;
            /** Parallel Tools */
            parallel_tools?: boolean | null;
            reasoning?: components["schemas"]["Reasoning"] | null;
            structured_output?: components["schemas"]["StructuredOutput"] | null;
            tool_calling?: components["schemas"]["ToolCalling"] | null;
        };
        /** ChatCompletionRequest */
        ChatCompletionRequest: {
            /**
             * Coire Wait For Model
             * @default true
             */
            coire_wait_for_model: boolean;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /**
             * Model
             * Format: uuid
             */
            model: string;
            /** Response Format */
            response_format?: {
                [key: string]: unknown;
            } | null;
            /** Stop */
            stop?: string | string[] | null;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /** Temperature */
            temperature?: number | null;
            /** Tool Choice */
            tool_choice?: unknown;
            /** Tools */
            tools?: {
                [key: string]: unknown;
            }[] | null;
            /** Top P */
            top_p?: number | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string | null;
            /** Name */
            name?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Tool Call Id */
            tool_call_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChecksumManifest
         * @description The record of exactly what a verified copy contains.
         */
        ChecksumManifest: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Files */
            files?: components["schemas"]["ManifestFile"][];
            /** Repo Id */
            repo_id: string;
            /** Revision */
            revision: string;
            /** Slug */
            slug: string;
            /** Total Bytes */
            total_bytes: number;
        };
        /**
         * EngineState
         * @enum {string}
         */
        EngineState: "starting" | "ready" | "stopping" | "stopped" | "failed" | "orphan";
        /**
         * EngineStatus
         * @description A node's view of one engine.
         */
        EngineStatus: {
            /** Chat Template Sha256 */
            chat_template_sha256?: string | null;
            /** Cpu Percent */
            cpu_percent?: number | null;
            /** Engine Id */
            engine_id?: string | null;
            /**
             * Estimate Bytes
             * @default 0
             */
            estimate_bytes: number;
            /** Exit Code */
            exit_code?: number | null;
            /** Exit Output */
            exit_output?: string | null;
            /** Last Health At */
            last_health_at?: string | null;
            /** Load Seconds */
            load_seconds?: number | null;
            /** Pid */
            pid?: number | null;
            /** Port */
            port: number;
            /** Process Create Time */
            process_create_time?: number | null;
            /** Resident Bytes */
            resident_bytes?: number | null;
            /** Resident Delta Bytes */
            resident_delta_bytes?: number | null;
            /** Slug */
            slug?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            state: components["schemas"]["EngineState"];
            /** State Reason */
            state_reason?: string | null;
            /** Stopped At */
            stopped_at?: string | null;
        };
        /** GatewayModel */
        GatewayModel: {
            /** Coire Context Window */
            coire_context_window?: number | null;
            /** Coire Description */
            coire_description?: string | null;
            /**
             * Coire Load State
             * @enum {string}
             */
            coire_load_state: "loaded" | "loading" | "cold";
            /** Coire Tags */
            coire_tags?: string[];
            /** Created */
            created: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Object
             * @default model
             * @constant
             */
            object: "model";
            /**
             * Owned By
             * @default coire
             * @constant
             */
            owned_by: "coire";
        };
        /** GatewayModelList */
        GatewayModelList: {
            /** Data */
            data: components["schemas"]["GatewayModel"][];
            /**
             * Object
             * @default list
             * @constant
             */
            object: "list";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description `GET /health` — the aggregate. HTTP 503 when `status` is `unhealthy`.
         */
        HealthResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Links */
            links?: components["schemas"]["StudioDataLinkStatus"][];
            /** Nodes */
            nodes?: components["schemas"]["NodeHealth"][];
            /** Services */
            services?: components["schemas"]["ServiceHealth"][];
            status: components["schemas"]["HealthStatus"];
            /** Version */
            version: string;
        };
        /**
         * HealthStatus
         * @description Aggregate verdict for the control plane.
         * @enum {string}
         */
        HealthStatus: "healthy" | "degraded" | "unhealthy";
        /**
         * JobErrorKind
         * @enum {string}
         */
        JobErrorKind: "gated" | "not_found" | "network" | "checksum_mismatch" | "disk_full" | "cancelled" | "internal";
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "pull" | "import" | "verify";
        /**
         * JobStage
         * @enum {string}
         */
        JobStage: "queued" | "resolving" | "transferring" | "hashing" | "done" | "failed" | "cancelled";
        /**
         * JobStatus
         * @description A node's view of one unit of acquisition work.
         */
        JobStatus: {
            /**
             * Bytes Done
             * @default 0
             */
            bytes_done: number;
            /**
             * Bytes Total
             * @default 0
             */
            bytes_total: number;
            /** Error */
            error?: string | null;
            error_kind?: components["schemas"]["JobErrorKind"] | null;
            /**
             * Files Done
             * @default 0
             */
            files_done: number;
            /**
             * Files Total
             * @default 0
             */
            files_total: number;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            kind: components["schemas"]["JobKind"];
            manifest?: components["schemas"]["ChecksumManifest"] | null;
            /** Manifest Sha256 */
            manifest_sha256?: string | null;
            /** Mismatched Paths */
            mismatched_paths?: string[];
            /** Slug */
            slug: string;
            stage: components["schemas"]["JobStage"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Worker Cpu Percent */
            worker_cpu_percent?: number | null;
            /** Worker Pid */
            worker_pid?: number | null;
        };
        /**
         * LinkState
         * @enum {string}
         */
        LinkState: "unknown" | "up" | "down";
        /**
         * LoadState
         * @enum {string}
         */
        LoadState: "loaded" | "loading" | "cold";
        /** ManifestFile */
        ManifestFile: {
            /** Bytes */
            bytes: number;
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
            /** Upstream Sha256 */
            upstream_sha256?: string | null;
        };
        /** ModelAddRequest */
        ModelAddRequest: {
            /** Description */
            description?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Idle Ttl Seconds */
            idle_ttl_seconds?: number | null;
            /**
             * Placement Policy
             * @default single:auto
             */
            placement_policy: string;
            /** Repo Id */
            repo_id: string;
            /** Tags */
            tags?: components["schemas"]["Tag"][];
        };
        /**
         * ModelListing
         * @description The user-facing shape.
         *
         *     Deliberately narrow: no paths, no copies, no failure reasons, no repo id. What a user may
         *     see about a model is what the picker needs to choose one.
         */
        ModelListing: {
            capability_profile: components["schemas"]["CapabilityProfile"];
            /** Context Window */
            context_window?: number | null;
            /** Description */
            description?: string | null;
            /** Display Name */
            display_name: string;
            /** Estimated Warmup Seconds */
            estimated_warmup_seconds?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            load_state: components["schemas"]["LoadState"];
            /** Loaded On */
            loaded_on?: string[];
            /** Precision */
            precision: string;
            /** Tags */
            tags?: components["schemas"]["Tag"][];
        };
        /**
         * ModelUpdateRequest
         * @description Curation. Every field is optional; absent means unchanged.
         *
         *     `chat_template` is tri-state and cannot be expressed with a plain `| None` default, so
         *     absence is spelled with a sentinel: the field is `str | None` and "not supplied" is
         *     detected with `model_fields_set`.
         */
        ModelUpdateRequest: {
            capability_profile?: components["schemas"]["CapabilityProfileUpdate"] | null;
            /** Chat Template */
            chat_template?: string | null;
            /** Description */
            description?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Entitlement */
            entitlement?: string[] | null;
            /** Idle Ttl Seconds */
            idle_ttl_seconds?: number | null;
            /** Placement Policy */
            placement_policy?: string | null;
            /** Tags */
            tags?: components["schemas"]["Tag"][] | null;
            visibility?: components["schemas"]["Visibility"] | null;
        };
        /**
         * Node
         * @description A declared Studio, as persisted and returned by the registration endpoint.
         */
        Node: {
            /** Agent Version */
            agent_version: string;
            /** Disk Total Bytes */
            disk_total_bytes: number;
            /** Egress Address */
            egress_address?: string | null;
            /** Gpu Cores */
            gpu_cores?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Memory Total Bytes */
            memory_total_bytes: number;
            /**
             * Mesh Address
             * Format: ipv4
             */
            mesh_address: string;
            /** Name */
            name: string;
            /** @default unknown */
            reachability: components["schemas"]["Reachability"];
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            role: components["schemas"]["NodeRole"];
        };
        /**
         * NodeEndpointSet
         * @description Stable endpoint identities advertised by a v2 node agent.
         */
        NodeEndpointSet: {
            /**
             * Contract Version
             * @default 2
             * @constant
             */
            contract_version: 2;
            /** Control Host */
            control_host: string;
            /** Data Host */
            data_host?: string | null;
        };
        /**
         * NodeHealth
         * @description A node verdict evaluated using control-plane receipt time.
         */
        NodeHealth: {
            /** Clock Skew Seconds */
            clock_skew_seconds?: number | null;
            /** Fresh */
            fresh: boolean;
            /** Heartbeat Latency Ms */
            heartbeat_latency_ms?: number | null;
            /**
             * Last Observed At
             * Format: date-time
             */
            last_observed_at: string;
            /** Last Success At */
            last_success_at?: string | null;
            /** Name */
            name: string;
            observation?: components["schemas"]["NodeStatus"] | null;
            /** Process State Verified */
            process_state_verified: boolean;
            /** Reason */
            reason?: string | null;
            /** Seconds Since Heartbeat */
            seconds_since_heartbeat: number;
            verdict: components["schemas"]["Reachability"];
        };
        /**
         * NodePath
         * @description Which listener answered. `FALLBACK` means the egress path was used (FR-013b/c).
         * @enum {string}
         */
        NodePath: "mesh" | "fallback";
        /**
         * NodeRegistration
         * @description `POST /api/v1/nodes/register` request body.
         */
        NodeRegistration: {
            /** Agent Version */
            agent_version: string;
            /** Disk Total Bytes */
            disk_total_bytes: number;
            /** Egress Address */
            egress_address?: string | null;
            /** Gpu Cores */
            gpu_cores?: number | null;
            /** Memory Total Bytes */
            memory_total_bytes: number;
            /**
             * Mesh Address
             * Format: ipv4
             */
            mesh_address: string;
            /** Name */
            name: string;
            /**
             * Token
             * Format: password
             */
            token: string;
        };
        /**
         * NodeRegistrationV2
         * @description Separated-fabric registration shape (feature 022).
         */
        NodeRegistrationV2: {
            /** Agent Version */
            agent_version: string;
            /** Disk Total Bytes */
            disk_total_bytes: number;
            endpoints: components["schemas"]["NodeEndpointSet"];
            /** Gpu Cores */
            gpu_cores?: number | null;
            /** Memory Total Bytes */
            memory_total_bytes: number;
            /** Name */
            name: string;
            /**
             * Token
             * Format: password
             */
            token: string;
        };
        /**
         * NodeRole
         * @enum {string}
         */
        NodeRole: "studio" | "core";
        /**
         * NodeStatus
         * @description `GET /node/health` on a Studio, port 9400. Requires the node's bearer token (FR-013).
         */
        NodeStatus: {
            /** Agent Cpu Percent */
            agent_cpu_percent: number;
            /** Agent Rss Bytes */
            agent_rss_bytes: number;
            /** Agent Version */
            agent_version: string;
            /** Collection Budget Ok */
            collection_budget_ok: boolean;
            /**
             * Collection Duration Ms
             * @default 0
             */
            collection_duration_ms: number;
            /** Cpu Percent */
            cpu_percent: number;
            /** Disk Free Bytes */
            disk_free_bytes: number;
            /** Disk Total Bytes */
            disk_total_bytes: number;
            /** Engines */
            engines?: components["schemas"]["EngineStatus"][];
            /** Gpu Percent */
            gpu_percent?: number | null;
            /** Jobs */
            jobs?: components["schemas"]["JobStatus"][];
            /**
             * Memory Budget Bytes
             * @default 0
             */
            memory_budget_bytes: number;
            /**
             * Memory Committed Bytes
             * @default 0
             */
            memory_committed_bytes: number;
            /** Memory Free Bytes */
            memory_free_bytes: number;
            /** Memory Total Bytes */
            memory_total_bytes: number;
            /** Name */
            name: string;
            /**
             * Optional Sampling Backoff
             * @default 1
             */
            optional_sampling_backoff: number;
            path: components["schemas"]["NodePath"];
            /**
             * Sampled At
             * Format: date-time
             */
            sampled_at: string;
            /**
             * Store Free Bytes
             * @default 0
             */
            store_free_bytes: number;
            /** @default unknown */
            thermal_state: components["schemas"]["ThermalState"];
            /** Uptime Seconds */
            uptime_seconds: number;
        };
        /**
         * NodeV2
         * @description Persisted node response matching a v2 registration request.
         */
        NodeV2: {
            /** Agent Version */
            agent_version: string;
            /** Disk Total Bytes */
            disk_total_bytes: number;
            endpoints: components["schemas"]["NodeEndpointSet"];
            /** Gpu Cores */
            gpu_cores?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Memory Total Bytes */
            memory_total_bytes: number;
            /** Name */
            name: string;
            /** @default unknown */
            reachability: components["schemas"]["Reachability"];
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            role: components["schemas"]["NodeRole"];
        };
        /**
         * RdmaState
         * @enum {string}
         */
        RdmaState: "unknown" | "up" | "degraded" | "down";
        /**
         * Reachability
         * @description Feature 000 sets only HEALTHY/UNREACHABLE/UNKNOWN; DEGRADED arrives with feature 009.
         * @enum {string}
         */
        Reachability: "healthy" | "degraded" | "unreachable" | "unknown";
        /**
         * ReadyResponse
         * @description `GET /ready` — liveness only. Deliberately checks nothing external (FR-009).
         */
        ReadyResponse: {
            /**
             * Ready
             * @default true
             * @constant
             */
            ready: true;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /**
         * Reasoning
         * @enum {string}
         */
        Reasoning: "none" | "thinking" | "hybrid";
        /**
         * ServiceHealth
         * @description One dependency's health as observed by the aggregate probe.
         */
        ServiceHealth: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Detail */
            detail?: string | null;
            /** Healthy */
            healthy: boolean;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Name */
            name: string;
        };
        /**
         * StructuredOutput
         * @enum {string}
         */
        StructuredOutput: "none" | "json_mode" | "json_schema";
        /** StudioDataLinkStatus */
        StudioDataLinkStatus: {
            /** Bandwidth Bytes Per Second */
            bandwidth_bytes_per_second?: number | null;
            /** @default unknown */
            ip_state: components["schemas"]["LinkState"];
            /** Latency Ms */
            latency_ms?: number | null;
            /** Measured At */
            measured_at?: string | null;
            /** Node A */
            node_a: string;
            /** Node B */
            node_b: string;
            /** @default unknown */
            rdma_state: components["schemas"]["RdmaState"];
            /** Reason */
            reason?: string | null;
        };
        /**
         * Tag
         * @description The picker's grouping vocabulary (ARCHITECTURE.md section 3.2).
         * @enum {string}
         */
        Tag: "coding" | "general" | "reasoning" | "vision" | "image";
        /**
         * ThermalState
         * @enum {string}
         */
        ThermalState: "nominal" | "fair" | "serious" | "critical" | "unknown";
        /**
         * ToolCalling
         * @enum {string}
         */
        ToolCalling: "none" | "prompted" | "native";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Visibility
         * @enum {string}
         */
        Visibility: "admin_only" | "published";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_api_v1_admin_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                target_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_engines_api_v1_admin_engines_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_engine_api_v1_admin_engines__engine_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                engine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unload_engine_api_v1_admin_engines__engine_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                engine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_admin_models_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_model_api_v1_admin_models_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_v1_admin_models__model_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_api_v1_admin_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_api_v1_admin_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_admin_models__model_id__job_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_model_api_v1_admin_models__model_id__load_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: string;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_model_api_v1_admin_models__model_id__retire_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_model_api_v1_admin_models__model_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    studio_data_link_api_v1_admin_network_links_studios_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioDataLinkStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_nodes_api_v1_admin_nodes_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListing"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_node_api_v1_nodes_register_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeRegistration"] | components["schemas"]["NodeRegistrationV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"] | components["schemas"]["NodeV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    chat_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anthropic_messages_v1_messages_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnthropicMessagesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayModelList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
