"""Shared wire models, loaded on demand without constructing unused service schemas."""

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from coire_core.models.acquisition import (
        AcquisitionRequest,
        AcquisitionStage,
        AcquisitionState,
        AcquisitionWorkflow,
        FitDecision,
        InspectionResult,
        ModelVariant,
        Precision,
        QuantizationMode,
        Reservation,
        ReservationRequest,
        ReservationState,
        StageResult,
        StageStatus,
        ValidationOutcome,
        ValidationResult,
        VariantPublication,
        VariantRecipe,
        VariantState,
    )
    from coire_core.models.auth import (
        ActorType,
        ApiKey,
        ApiKeyCreate,
        ApiKeyIssued,
        ApiKeyUpdate,
        AuthPrincipal,
        AuthScope,
        Entitlement,
        QuotaStatus,
        User,
        UserCreate,
        UserRole,
        UserUpdate,
    )
    from coire_core.models.chat import (
        ChatAttachmentChanged,
        ChatConversation,
        ChatConversationCreate,
        ChatConversationDeleted,
        ChatConversationDetail,
        ChatConversationPage,
        ChatConversationUpdate,
        ChatDeleteRequest,
        ChatDeletionResult,
        ChatEvent,
        ChatMessageDelta,
        ChatMessagePageQuery,
        ChatPageQuery,
        ChatPickerEntry,
        ChatPickerQuery,
        ChatPickerResponse,
        ChatRunActivity,
        ChatRunActivityStatus,
        ChatSnapshot,
        ChatStopRequest,
        ChatTurn,
        ChatTurnAccepted,
        ChatTurnCreate,
        ChatTurnDetail,
        ChatTurnResult,
        ChatTurnStatus,
        ChatTurnTerminal,
        ChatUsage,
    )
    from coire_core.models.chat import (
        ChatMessage as NativeChatMessage,
    )
    from coire_core.models.conversation import (
        Conversation,
        ConversationMessage,
        ImagePart,
        TextPart,
    )
    from coire_core.models.failover import (
        ElectionVoteGrant,
        ElectionVoteRequest,
        FailoverAccessVerifier,
        FailoverEvent,
        FailoverEventBatch,
        FailoverEventKind,
        FailoverHeartbeat,
        FailoverLease,
        FailoverMember,
        FailoverMembershipConfig,
        FailoverModel,
        FailoverOverride,
        FailoverOverrideKind,
        FailoverRelayRequest,
        FailoverResidentEngine,
        FailoverSnapshot,
        FailoverStatus,
        FailoverTier,
        HandbackNotice,
        PromotionProof,
    )
    from coire_core.models.files import (
        ChatAttachment,
        ChatAttachmentSelection,
        ChatPreviewAsset,
        FileProcessAsset,
        FileProcessCancel,
        FileProcessJob,
        FileProcessRequest,
        FileProcessResult,
        FileProcessStatus,
        FilePurgeResult,
        FileWorkerHealth,
    )
    from coire_core.models.gateway import (
        AnthropicMessage,
        AnthropicMessagesRequest,
        ChatCompletionRequest,
        ChatMessage,
        GatewayModel,
        GatewayModelList,
        GatewayProtocol,
        OpenAIImagePart,
        OpenAIImageURL,
        OpenAITextPart,
        ProblemDetails,
        UsageOutcome,
        UsageRecord,
    )
    from coire_core.models.harness import (
        AgentProfile,
        CategoryScores,
        ContextBudget,
        EvaluationVerdict,
        HarnessEvaluation,
        HarnessEvaluationRequest,
        HarnessEvaluationSubmission,
        HarnessEvaluationTarget,
        HarnessMessage,
        HarnessRunRequest,
        HarnessRunResult,
        HarnessStrategy,
        ProfileName,
        TaskClass,
        ToolCall,
    )
    from coire_core.models.instance import (
        TERMINAL_INSTANCE_STATES,
        ClusterNodeState,
        ClusterState,
        InstanceCreate,
        InstanceMember,
        InstanceState,
        InstanceTransition,
        ModelInstance,
        NodeDeclaration,
        NodeRegistrationCredential,
    )
    from coire_core.models.link import (
        ControlPathStatus,
        LinkState,
        RdmaState,
        StudioDataLinkStatus,
    )
    from coire_core.models.ops import (
        EmptyOpsParameters,
        InstanceLoadAction,
        InstanceLoadParameters,
        InstanceUnloadAction,
        ModelPinAction,
        ModelUnpinAction,
        OpsActionPrecondition,
        OpsConfirmRequest,
        OpsConversation,
        OpsConversationCreate,
        OpsConversationDetail,
        OpsConversationState,
        OpsDeclineRequest,
        OpsMessage,
        OpsMessageCreate,
        OpsMessageRole,
        OpsProposal,
        OpsProposalIssued,
        OpsProposalState,
        OpsProposalSubmission,
        OpsServiceTurnRequest,
        OpsSession,
        OpsSessionRegistration,
        OpsSessionState,
        OpsTurnResponse,
        OpsTurnStatus,
        ResolvedOpsAction,
        RunKillAction,
    )
    from coire_core.models.placement import (
        LedgerUpdate,
        MemoryLedger,
        MemoryReservation,
        MemoryReservationState,
        OccupantReason,
        PinUpdate,
        PlacementDecision,
        PlacementOccupant,
        PlacementRequest,
        PlacementState,
        ReservationHolder,
    )
    from coire_core.models.registry import EngineBackend, VisualCapability
    from coire_core.models.runs import (
        TERMINAL_RUN_STATES,
        AgentRun,
        AgentRunCreate,
        AgentRunState,
        AgentRunTransition,
        RunActivity,
        RunActivityPage,
        RunActivityTool,
        RunCollectedResult,
        RunCommandState,
        RunContainerCreate,
        RunContainerObservation,
        RunContainerStatus,
        RunKillRequest,
        RunLimits,
        RunLogChunk,
        RunOperation,
        RunProblemCode,
        RunReconcileRequest,
        RunReconcileResult,
        RunResourceUsage,
        RunTokenScope,
        RunTokenStatus,
    )
    from coire_core.models.sharding import (
        BenchmarkCommand,
        BenchmarkMeasurement,
        BenchmarkRequest,
        BenchmarkResult,
        BenchmarkRun,
        BenchmarkRunState,
        LinkObservation,
        LinkProbeCommand,
        LinkProbeRequest,
        ProbeOutcome,
        ProbeTransport,
        ShardCapabilityRequest,
        ShardCapabilityResult,
        ShardGroupCommand,
        ShardGroupState,
        ShardGroupStatus,
        ShardingMode,
        ShardRank,
        StudioLinkProjection,
    )

_EXPORTS: dict[str, tuple[str, str]] = {
    "TERMINAL_INSTANCE_STATES": ("coire_core.models.instance", "TERMINAL_INSTANCE_STATES"),
    "TERMINAL_RUN_STATES": ("coire_core.models.runs", "TERMINAL_RUN_STATES"),
    "AcquisitionRequest": ("coire_core.models.acquisition", "AcquisitionRequest"),
    "AcquisitionStage": ("coire_core.models.acquisition", "AcquisitionStage"),
    "AcquisitionState": ("coire_core.models.acquisition", "AcquisitionState"),
    "AcquisitionWorkflow": ("coire_core.models.acquisition", "AcquisitionWorkflow"),
    "ActorType": ("coire_core.models.auth", "ActorType"),
    "AgentProfile": ("coire_core.models.harness", "AgentProfile"),
    "AgentRun": ("coire_core.models.runs", "AgentRun"),
    "AgentRunCreate": ("coire_core.models.runs", "AgentRunCreate"),
    "AgentRunState": ("coire_core.models.runs", "AgentRunState"),
    "AgentRunTransition": ("coire_core.models.runs", "AgentRunTransition"),
    "AnthropicMessage": ("coire_core.models.gateway", "AnthropicMessage"),
    "AnthropicMessagesRequest": ("coire_core.models.gateway", "AnthropicMessagesRequest"),
    "ApiKey": ("coire_core.models.auth", "ApiKey"),
    "ApiKeyCreate": ("coire_core.models.auth", "ApiKeyCreate"),
    "ApiKeyIssued": ("coire_core.models.auth", "ApiKeyIssued"),
    "ApiKeyUpdate": ("coire_core.models.auth", "ApiKeyUpdate"),
    "AuthPrincipal": ("coire_core.models.auth", "AuthPrincipal"),
    "AuthScope": ("coire_core.models.auth", "AuthScope"),
    "BenchmarkCommand": ("coire_core.models.sharding", "BenchmarkCommand"),
    "BenchmarkMeasurement": ("coire_core.models.sharding", "BenchmarkMeasurement"),
    "BenchmarkRequest": ("coire_core.models.sharding", "BenchmarkRequest"),
    "BenchmarkResult": ("coire_core.models.sharding", "BenchmarkResult"),
    "BenchmarkRun": ("coire_core.models.sharding", "BenchmarkRun"),
    "BenchmarkRunState": ("coire_core.models.sharding", "BenchmarkRunState"),
    "CategoryScores": ("coire_core.models.harness", "CategoryScores"),
    "ChatAttachment": ("coire_core.models.files", "ChatAttachment"),
    "ChatAttachmentChanged": ("coire_core.models.chat", "ChatAttachmentChanged"),
    "ChatAttachmentSelection": ("coire_core.models.files", "ChatAttachmentSelection"),
    "ChatCompletionRequest": ("coire_core.models.gateway", "ChatCompletionRequest"),
    "ChatConversation": ("coire_core.models.chat", "ChatConversation"),
    "ChatConversationCreate": ("coire_core.models.chat", "ChatConversationCreate"),
    "ChatConversationDeleted": ("coire_core.models.chat", "ChatConversationDeleted"),
    "ChatConversationDetail": ("coire_core.models.chat", "ChatConversationDetail"),
    "ChatConversationPage": ("coire_core.models.chat", "ChatConversationPage"),
    "ChatConversationUpdate": ("coire_core.models.chat", "ChatConversationUpdate"),
    "ChatDeleteRequest": ("coire_core.models.chat", "ChatDeleteRequest"),
    "ChatDeletionResult": ("coire_core.models.chat", "ChatDeletionResult"),
    "ChatEvent": ("coire_core.models.chat", "ChatEvent"),
    "ChatMessage": ("coire_core.models.gateway", "ChatMessage"),
    "ChatMessageDelta": ("coire_core.models.chat", "ChatMessageDelta"),
    "ChatMessagePageQuery": ("coire_core.models.chat", "ChatMessagePageQuery"),
    "ChatPageQuery": ("coire_core.models.chat", "ChatPageQuery"),
    "ChatPickerEntry": ("coire_core.models.chat", "ChatPickerEntry"),
    "ChatPickerQuery": ("coire_core.models.chat", "ChatPickerQuery"),
    "ChatPickerResponse": ("coire_core.models.chat", "ChatPickerResponse"),
    "ChatPreviewAsset": ("coire_core.models.files", "ChatPreviewAsset"),
    "ChatRunActivity": ("coire_core.models.chat", "ChatRunActivity"),
    "ChatRunActivityStatus": ("coire_core.models.chat", "ChatRunActivityStatus"),
    "ChatSnapshot": ("coire_core.models.chat", "ChatSnapshot"),
    "ChatStopRequest": ("coire_core.models.chat", "ChatStopRequest"),
    "ChatTurn": ("coire_core.models.chat", "ChatTurn"),
    "ChatTurnAccepted": ("coire_core.models.chat", "ChatTurnAccepted"),
    "ChatTurnCreate": ("coire_core.models.chat", "ChatTurnCreate"),
    "ChatTurnDetail": ("coire_core.models.chat", "ChatTurnDetail"),
    "ChatTurnResult": ("coire_core.models.chat", "ChatTurnResult"),
    "ChatTurnStatus": ("coire_core.models.chat", "ChatTurnStatus"),
    "ChatTurnTerminal": ("coire_core.models.chat", "ChatTurnTerminal"),
    "ChatUsage": ("coire_core.models.chat", "ChatUsage"),
    "ClusterNodeState": ("coire_core.models.instance", "ClusterNodeState"),
    "ClusterState": ("coire_core.models.instance", "ClusterState"),
    "ContextBudget": ("coire_core.models.harness", "ContextBudget"),
    "ControlPathStatus": ("coire_core.models.link", "ControlPathStatus"),
    "Conversation": ("coire_core.models.conversation", "Conversation"),
    "ConversationMessage": ("coire_core.models.conversation", "ConversationMessage"),
    "ElectionVoteGrant": ("coire_core.models.failover", "ElectionVoteGrant"),
    "ElectionVoteRequest": ("coire_core.models.failover", "ElectionVoteRequest"),
    "EmptyOpsParameters": ("coire_core.models.ops", "EmptyOpsParameters"),
    "EngineBackend": ("coire_core.models.registry", "EngineBackend"),
    "Entitlement": ("coire_core.models.auth", "Entitlement"),
    "EvaluationVerdict": ("coire_core.models.harness", "EvaluationVerdict"),
    "FailoverAccessVerifier": ("coire_core.models.failover", "FailoverAccessVerifier"),
    "FailoverEvent": ("coire_core.models.failover", "FailoverEvent"),
    "FailoverEventBatch": ("coire_core.models.failover", "FailoverEventBatch"),
    "FailoverEventKind": ("coire_core.models.failover", "FailoverEventKind"),
    "FailoverHeartbeat": ("coire_core.models.failover", "FailoverHeartbeat"),
    "FailoverLease": ("coire_core.models.failover", "FailoverLease"),
    "FailoverMember": ("coire_core.models.failover", "FailoverMember"),
    "FailoverMembershipConfig": ("coire_core.models.failover", "FailoverMembershipConfig"),
    "FailoverModel": ("coire_core.models.failover", "FailoverModel"),
    "FailoverOverride": ("coire_core.models.failover", "FailoverOverride"),
    "FailoverOverrideKind": ("coire_core.models.failover", "FailoverOverrideKind"),
    "FailoverRelayRequest": ("coire_core.models.failover", "FailoverRelayRequest"),
    "FailoverResidentEngine": ("coire_core.models.failover", "FailoverResidentEngine"),
    "FailoverSnapshot": ("coire_core.models.failover", "FailoverSnapshot"),
    "FailoverStatus": ("coire_core.models.failover", "FailoverStatus"),
    "FailoverTier": ("coire_core.models.failover", "FailoverTier"),
    "FileProcessAsset": ("coire_core.models.files", "FileProcessAsset"),
    "FileProcessCancel": ("coire_core.models.files", "FileProcessCancel"),
    "FileProcessJob": ("coire_core.models.files", "FileProcessJob"),
    "FileProcessRequest": ("coire_core.models.files", "FileProcessRequest"),
    "FileProcessResult": ("coire_core.models.files", "FileProcessResult"),
    "FileProcessStatus": ("coire_core.models.files", "FileProcessStatus"),
    "FilePurgeResult": ("coire_core.models.files", "FilePurgeResult"),
    "FileWorkerHealth": ("coire_core.models.files", "FileWorkerHealth"),
    "FitDecision": ("coire_core.models.acquisition", "FitDecision"),
    "GatewayModel": ("coire_core.models.gateway", "GatewayModel"),
    "GatewayModelList": ("coire_core.models.gateway", "GatewayModelList"),
    "GatewayProtocol": ("coire_core.models.gateway", "GatewayProtocol"),
    "HandbackNotice": ("coire_core.models.failover", "HandbackNotice"),
    "HarnessEvaluation": ("coire_core.models.harness", "HarnessEvaluation"),
    "HarnessEvaluationRequest": ("coire_core.models.harness", "HarnessEvaluationRequest"),
    "HarnessEvaluationSubmission": ("coire_core.models.harness", "HarnessEvaluationSubmission"),
    "HarnessEvaluationTarget": ("coire_core.models.harness", "HarnessEvaluationTarget"),
    "HarnessMessage": ("coire_core.models.harness", "HarnessMessage"),
    "HarnessRunRequest": ("coire_core.models.harness", "HarnessRunRequest"),
    "HarnessRunResult": ("coire_core.models.harness", "HarnessRunResult"),
    "HarnessStrategy": ("coire_core.models.harness", "HarnessStrategy"),
    "ImagePart": ("coire_core.models.conversation", "ImagePart"),
    "InspectionResult": ("coire_core.models.acquisition", "InspectionResult"),
    "InstanceCreate": ("coire_core.models.instance", "InstanceCreate"),
    "InstanceLoadAction": ("coire_core.models.ops", "InstanceLoadAction"),
    "InstanceLoadParameters": ("coire_core.models.ops", "InstanceLoadParameters"),
    "InstanceMember": ("coire_core.models.instance", "InstanceMember"),
    "InstanceState": ("coire_core.models.instance", "InstanceState"),
    "InstanceTransition": ("coire_core.models.instance", "InstanceTransition"),
    "InstanceUnloadAction": ("coire_core.models.ops", "InstanceUnloadAction"),
    "LedgerUpdate": ("coire_core.models.placement", "LedgerUpdate"),
    "LinkObservation": ("coire_core.models.sharding", "LinkObservation"),
    "LinkProbeCommand": ("coire_core.models.sharding", "LinkProbeCommand"),
    "LinkProbeRequest": ("coire_core.models.sharding", "LinkProbeRequest"),
    "LinkState": ("coire_core.models.link", "LinkState"),
    "MemoryLedger": ("coire_core.models.placement", "MemoryLedger"),
    "MemoryReservation": ("coire_core.models.placement", "MemoryReservation"),
    "MemoryReservationState": ("coire_core.models.placement", "MemoryReservationState"),
    "ModelInstance": ("coire_core.models.instance", "ModelInstance"),
    "ModelPinAction": ("coire_core.models.ops", "ModelPinAction"),
    "ModelUnpinAction": ("coire_core.models.ops", "ModelUnpinAction"),
    "ModelVariant": ("coire_core.models.acquisition", "ModelVariant"),
    "NativeChatMessage": ("coire_core.models.chat", "ChatMessage"),
    "NodeDeclaration": ("coire_core.models.instance", "NodeDeclaration"),
    "NodeRegistrationCredential": ("coire_core.models.instance", "NodeRegistrationCredential"),
    "OccupantReason": ("coire_core.models.placement", "OccupantReason"),
    "OpenAIImagePart": ("coire_core.models.gateway", "OpenAIImagePart"),
    "OpenAIImageURL": ("coire_core.models.gateway", "OpenAIImageURL"),
    "OpenAITextPart": ("coire_core.models.gateway", "OpenAITextPart"),
    "OpsActionPrecondition": ("coire_core.models.ops", "OpsActionPrecondition"),
    "OpsConfirmRequest": ("coire_core.models.ops", "OpsConfirmRequest"),
    "OpsConversation": ("coire_core.models.ops", "OpsConversation"),
    "OpsConversationCreate": ("coire_core.models.ops", "OpsConversationCreate"),
    "OpsConversationDetail": ("coire_core.models.ops", "OpsConversationDetail"),
    "OpsConversationState": ("coire_core.models.ops", "OpsConversationState"),
    "OpsDeclineRequest": ("coire_core.models.ops", "OpsDeclineRequest"),
    "OpsMessage": ("coire_core.models.ops", "OpsMessage"),
    "OpsMessageCreate": ("coire_core.models.ops", "OpsMessageCreate"),
    "OpsMessageRole": ("coire_core.models.ops", "OpsMessageRole"),
    "OpsProposal": ("coire_core.models.ops", "OpsProposal"),
    "OpsProposalIssued": ("coire_core.models.ops", "OpsProposalIssued"),
    "OpsProposalState": ("coire_core.models.ops", "OpsProposalState"),
    "OpsProposalSubmission": ("coire_core.models.ops", "OpsProposalSubmission"),
    "OpsServiceTurnRequest": ("coire_core.models.ops", "OpsServiceTurnRequest"),
    "OpsSession": ("coire_core.models.ops", "OpsSession"),
    "OpsSessionRegistration": ("coire_core.models.ops", "OpsSessionRegistration"),
    "OpsSessionState": ("coire_core.models.ops", "OpsSessionState"),
    "OpsTurnResponse": ("coire_core.models.ops", "OpsTurnResponse"),
    "OpsTurnStatus": ("coire_core.models.ops", "OpsTurnStatus"),
    "PinUpdate": ("coire_core.models.placement", "PinUpdate"),
    "PlacementDecision": ("coire_core.models.placement", "PlacementDecision"),
    "PlacementOccupant": ("coire_core.models.placement", "PlacementOccupant"),
    "PlacementRequest": ("coire_core.models.placement", "PlacementRequest"),
    "PlacementState": ("coire_core.models.placement", "PlacementState"),
    "Precision": ("coire_core.models.acquisition", "Precision"),
    "ProbeOutcome": ("coire_core.models.sharding", "ProbeOutcome"),
    "ProbeTransport": ("coire_core.models.sharding", "ProbeTransport"),
    "ProblemDetails": ("coire_core.models.gateway", "ProblemDetails"),
    "ProfileName": ("coire_core.models.harness", "ProfileName"),
    "PromotionProof": ("coire_core.models.failover", "PromotionProof"),
    "QuantizationMode": ("coire_core.models.acquisition", "QuantizationMode"),
    "QuotaStatus": ("coire_core.models.auth", "QuotaStatus"),
    "RdmaState": ("coire_core.models.link", "RdmaState"),
    "Reservation": ("coire_core.models.acquisition", "Reservation"),
    "ReservationHolder": ("coire_core.models.placement", "ReservationHolder"),
    "ReservationRequest": ("coire_core.models.acquisition", "ReservationRequest"),
    "ReservationState": ("coire_core.models.acquisition", "ReservationState"),
    "ResolvedOpsAction": ("coire_core.models.ops", "ResolvedOpsAction"),
    "RunActivity": ("coire_core.models.runs", "RunActivity"),
    "RunActivityPage": ("coire_core.models.runs", "RunActivityPage"),
    "RunActivityTool": ("coire_core.models.runs", "RunActivityTool"),
    "RunCollectedResult": ("coire_core.models.runs", "RunCollectedResult"),
    "RunCommandState": ("coire_core.models.runs", "RunCommandState"),
    "RunContainerCreate": ("coire_core.models.runs", "RunContainerCreate"),
    "RunContainerObservation": ("coire_core.models.runs", "RunContainerObservation"),
    "RunContainerStatus": ("coire_core.models.runs", "RunContainerStatus"),
    "RunKillAction": ("coire_core.models.ops", "RunKillAction"),
    "RunKillRequest": ("coire_core.models.runs", "RunKillRequest"),
    "RunLimits": ("coire_core.models.runs", "RunLimits"),
    "RunLogChunk": ("coire_core.models.runs", "RunLogChunk"),
    "RunOperation": ("coire_core.models.runs", "RunOperation"),
    "RunProblemCode": ("coire_core.models.runs", "RunProblemCode"),
    "RunReconcileRequest": ("coire_core.models.runs", "RunReconcileRequest"),
    "RunReconcileResult": ("coire_core.models.runs", "RunReconcileResult"),
    "RunResourceUsage": ("coire_core.models.runs", "RunResourceUsage"),
    "RunTokenScope": ("coire_core.models.runs", "RunTokenScope"),
    "RunTokenStatus": ("coire_core.models.runs", "RunTokenStatus"),
    "ShardCapabilityRequest": ("coire_core.models.sharding", "ShardCapabilityRequest"),
    "ShardCapabilityResult": ("coire_core.models.sharding", "ShardCapabilityResult"),
    "ShardGroupCommand": ("coire_core.models.sharding", "ShardGroupCommand"),
    "ShardGroupState": ("coire_core.models.sharding", "ShardGroupState"),
    "ShardGroupStatus": ("coire_core.models.sharding", "ShardGroupStatus"),
    "ShardRank": ("coire_core.models.sharding", "ShardRank"),
    "ShardingMode": ("coire_core.models.sharding", "ShardingMode"),
    "StageResult": ("coire_core.models.acquisition", "StageResult"),
    "StageStatus": ("coire_core.models.acquisition", "StageStatus"),
    "StudioDataLinkStatus": ("coire_core.models.link", "StudioDataLinkStatus"),
    "StudioLinkProjection": ("coire_core.models.sharding", "StudioLinkProjection"),
    "TaskClass": ("coire_core.models.harness", "TaskClass"),
    "TextPart": ("coire_core.models.conversation", "TextPart"),
    "ToolCall": ("coire_core.models.harness", "ToolCall"),
    "UsageOutcome": ("coire_core.models.gateway", "UsageOutcome"),
    "UsageRecord": ("coire_core.models.gateway", "UsageRecord"),
    "User": ("coire_core.models.auth", "User"),
    "UserCreate": ("coire_core.models.auth", "UserCreate"),
    "UserRole": ("coire_core.models.auth", "UserRole"),
    "UserUpdate": ("coire_core.models.auth", "UserUpdate"),
    "ValidationOutcome": ("coire_core.models.acquisition", "ValidationOutcome"),
    "ValidationResult": ("coire_core.models.acquisition", "ValidationResult"),
    "VariantPublication": ("coire_core.models.acquisition", "VariantPublication"),
    "VariantRecipe": ("coire_core.models.acquisition", "VariantRecipe"),
    "VariantState": ("coire_core.models.acquisition", "VariantState"),
    "VisualCapability": ("coire_core.models.registry", "VisualCapability"),
}

__all__ = [
    "TERMINAL_INSTANCE_STATES",
    "TERMINAL_RUN_STATES",
    "AcquisitionRequest",
    "AcquisitionStage",
    "AcquisitionState",
    "AcquisitionWorkflow",
    "ActorType",
    "AgentProfile",
    "AgentRun",
    "AgentRunCreate",
    "AgentRunState",
    "AgentRunTransition",
    "AnthropicMessage",
    "AnthropicMessagesRequest",
    "ApiKey",
    "ApiKeyCreate",
    "ApiKeyIssued",
    "ApiKeyUpdate",
    "AuthPrincipal",
    "AuthScope",
    "BenchmarkCommand",
    "BenchmarkMeasurement",
    "BenchmarkRequest",
    "BenchmarkResult",
    "BenchmarkRun",
    "BenchmarkRunState",
    "CategoryScores",
    "ChatAttachment",
    "ChatAttachmentChanged",
    "ChatAttachmentSelection",
    "ChatCompletionRequest",
    "ChatConversation",
    "ChatConversationCreate",
    "ChatConversationDeleted",
    "ChatConversationDetail",
    "ChatConversationPage",
    "ChatConversationUpdate",
    "ChatDeleteRequest",
    "ChatDeletionResult",
    "ChatEvent",
    "ChatMessage",
    "ChatMessageDelta",
    "ChatMessagePageQuery",
    "ChatPageQuery",
    "ChatPickerEntry",
    "ChatPickerQuery",
    "ChatPickerResponse",
    "ChatPreviewAsset",
    "ChatRunActivity",
    "ChatRunActivityStatus",
    "ChatSnapshot",
    "ChatStopRequest",
    "ChatTurn",
    "ChatTurnAccepted",
    "ChatTurnCreate",
    "ChatTurnDetail",
    "ChatTurnResult",
    "ChatTurnStatus",
    "ChatTurnTerminal",
    "ChatUsage",
    "ClusterNodeState",
    "ClusterState",
    "ContextBudget",
    "ControlPathStatus",
    "Conversation",
    "ConversationMessage",
    "ElectionVoteGrant",
    "ElectionVoteRequest",
    "EmptyOpsParameters",
    "EngineBackend",
    "Entitlement",
    "EvaluationVerdict",
    "FailoverAccessVerifier",
    "FailoverEvent",
    "FailoverEventBatch",
    "FailoverEventKind",
    "FailoverHeartbeat",
    "FailoverLease",
    "FailoverMember",
    "FailoverMembershipConfig",
    "FailoverModel",
    "FailoverOverride",
    "FailoverOverrideKind",
    "FailoverRelayRequest",
    "FailoverResidentEngine",
    "FailoverSnapshot",
    "FailoverStatus",
    "FailoverTier",
    "FileProcessAsset",
    "FileProcessCancel",
    "FileProcessJob",
    "FileProcessRequest",
    "FileProcessResult",
    "FileProcessStatus",
    "FilePurgeResult",
    "FileWorkerHealth",
    "FitDecision",
    "GatewayModel",
    "GatewayModelList",
    "GatewayProtocol",
    "HandbackNotice",
    "HarnessEvaluation",
    "HarnessEvaluationRequest",
    "HarnessEvaluationSubmission",
    "HarnessEvaluationTarget",
    "HarnessMessage",
    "HarnessRunRequest",
    "HarnessRunResult",
    "HarnessStrategy",
    "ImagePart",
    "InspectionResult",
    "InstanceCreate",
    "InstanceLoadAction",
    "InstanceLoadParameters",
    "InstanceMember",
    "InstanceState",
    "InstanceTransition",
    "InstanceUnloadAction",
    "LedgerUpdate",
    "LinkObservation",
    "LinkProbeCommand",
    "LinkProbeRequest",
    "LinkState",
    "MemoryLedger",
    "MemoryReservation",
    "MemoryReservationState",
    "ModelInstance",
    "ModelPinAction",
    "ModelUnpinAction",
    "ModelVariant",
    "NativeChatMessage",
    "NodeDeclaration",
    "NodeRegistrationCredential",
    "OccupantReason",
    "OpenAIImagePart",
    "OpenAIImageURL",
    "OpenAITextPart",
    "OpsActionPrecondition",
    "OpsConfirmRequest",
    "OpsConversation",
    "OpsConversationCreate",
    "OpsConversationDetail",
    "OpsConversationState",
    "OpsDeclineRequest",
    "OpsMessage",
    "OpsMessageCreate",
    "OpsMessageRole",
    "OpsProposal",
    "OpsProposalIssued",
    "OpsProposalState",
    "OpsProposalSubmission",
    "OpsServiceTurnRequest",
    "OpsSession",
    "OpsSessionRegistration",
    "OpsSessionState",
    "OpsTurnResponse",
    "OpsTurnStatus",
    "PinUpdate",
    "PlacementDecision",
    "PlacementOccupant",
    "PlacementRequest",
    "PlacementState",
    "Precision",
    "ProbeOutcome",
    "ProbeTransport",
    "ProblemDetails",
    "ProfileName",
    "PromotionProof",
    "QuantizationMode",
    "QuotaStatus",
    "RdmaState",
    "Reservation",
    "ReservationHolder",
    "ReservationRequest",
    "ReservationState",
    "ResolvedOpsAction",
    "RunActivity",
    "RunActivityPage",
    "RunActivityTool",
    "RunCollectedResult",
    "RunCommandState",
    "RunContainerCreate",
    "RunContainerObservation",
    "RunContainerStatus",
    "RunKillAction",
    "RunKillRequest",
    "RunLimits",
    "RunLogChunk",
    "RunOperation",
    "RunProblemCode",
    "RunReconcileRequest",
    "RunReconcileResult",
    "RunResourceUsage",
    "RunTokenScope",
    "RunTokenStatus",
    "ShardCapabilityRequest",
    "ShardCapabilityResult",
    "ShardGroupCommand",
    "ShardGroupState",
    "ShardGroupStatus",
    "ShardRank",
    "ShardingMode",
    "StageResult",
    "StageStatus",
    "StudioDataLinkStatus",
    "StudioLinkProjection",
    "TaskClass",
    "TextPart",
    "ToolCall",
    "UsageOutcome",
    "UsageRecord",
    "User",
    "UserCreate",
    "UserRole",
    "UserUpdate",
    "ValidationOutcome",
    "ValidationResult",
    "VariantPublication",
    "VariantRecipe",
    "VariantState",
    "VisualCapability",
]


def __getattr__(name: str) -> object:
    try:
        module, attribute = _EXPORTS[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    value: object = getattr(import_module(module), attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
