"""Shared wire models."""

from coire_core.models.acquisition import (
    AcquisitionRequest,
    AcquisitionStage,
    AcquisitionState,
    AcquisitionWorkflow,
    FitDecision,
    InspectionResult,
    ModelVariant,
    Precision,
    QuantizationMode,
    Reservation,
    ReservationRequest,
    ReservationState,
    StageResult,
    StageStatus,
    ValidationOutcome,
    ValidationResult,
    VariantPublication,
    VariantRecipe,
    VariantState,
)
from coire_core.models.gateway import (
    AnthropicMessage,
    AnthropicMessagesRequest,
    ChatCompletionRequest,
    ChatMessage,
    GatewayModel,
    GatewayModelList,
    GatewayProtocol,
    ProblemDetails,
    UsageOutcome,
    UsageRecord,
)
from coire_core.models.link import (
    ControlPathStatus,
    LinkState,
    RdmaState,
    StudioDataLinkStatus,
)

__all__ = [
    "AcquisitionRequest",
    "AcquisitionStage",
    "AcquisitionState",
    "AcquisitionWorkflow",
    "AnthropicMessage",
    "AnthropicMessagesRequest",
    "ChatCompletionRequest",
    "ChatMessage",
    "ControlPathStatus",
    "FitDecision",
    "GatewayModel",
    "GatewayModelList",
    "GatewayProtocol",
    "InspectionResult",
    "LinkState",
    "ModelVariant",
    "Precision",
    "ProblemDetails",
    "QuantizationMode",
    "RdmaState",
    "Reservation",
    "ReservationRequest",
    "ReservationState",
    "StageResult",
    "StageStatus",
    "StudioDataLinkStatus",
    "UsageOutcome",
    "UsageRecord",
    "ValidationOutcome",
    "ValidationResult",
    "VariantPublication",
    "VariantRecipe",
    "VariantState",
]
